name: Build and Push Docker Image

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GH_USERNAME }} --password-stdin

      - name: Build and push image
        run: |
          docker build -t ghcr.io/${{ secrets.GH_USERNAME }}/fastapi-app:latest .
          docker push ghcr.io/${{ secrets.GH_USERNAME }}/fastapi-app:latest